version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db: 
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_db
    ports:
      - 3306:3306    
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    










      # - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8000:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306